#ATENÇÃO: os credentials são sempre *encriptados*, esse arquivo é apenas um exemplo de visualização
#Aqui normalmente ficam as informações dos servers, mailers, oauths, basicamente tudo que for sensivel.
#Para criar o seu credentials, use o comando `EDITOR=nano rails credentials:edit`
default_server_config: &default_server_config
  sentry_access_token: 'dns do Raven'
  aws_s3:
    bucket_name:
    access_key_id:
    secret_access_key:
    region:

development:
  app_domain: 'localhost:3000'

test:
  app_domain: 'localhost:3000'

staging:
  app_domain: 'https://staging.seu_projeto.jera.com.br'
  <<: *default_server_config

production:
  app_domain: 'https://seu_projeto.com.br'
  <<: *default_server_config

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: # A secret_key_base é gerada automaticamente quando o credentials é criado e é unica por projeto
