default: &default
  adapter: mysql2
  host: localhost
  database: <%= ENV.fetch("MYSQL_DATABASE") || api_template_database %>
  username: <%= ENV.fetch("MYSQL_ROOT_NAME") || root %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") || root %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test: &test
  <<: *default
